name: udacity_app
channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.7.6
  - pytorch=1.11.0
  - torchvision=0.12.0
  - torchaudio=0.11.0
  - cudatoolkit=11.3

  - nodejs
  - voila
  - jupyterlab
  - notebook
  - ipykernel

  - pip
  - pip:
    - opencv-python-headless==4.5.3.56
    - matplotlib==3.4.3
    - numpy==1.21.2
    - pillow==7.0.0
    - bokeh==2.1.1
    - tqdm==4.63.0
    # Update ipywidgets to version 8.x.x for frontend compatibility
    - ipywidgets==8.1.2
    - livelossplot==0.5.4
    - pytest==7.1.1
    - pandas==1.3.5
    - seaborn==0.11.2
    # Update widgetsnbextension to its compatible version for ipywidgets 8.x.x
    - widgetsnbextension==4.0.10 
